### ISSUE TITLE
parameters.in: Lack of error handling if the list of Refinement criteria fields is inconsistent with list of min/max values for refinement window 

### ISSUE THREAD

**Issue by david-montiel-t** [prisms-center/phaseField#104]
The code does not produce a runtime error if the list of refinement criteria fields is inconsistent with the list of min/max values for refinement window. 

For instance, no error is produced in the following instance:

\# Set the fields used to determine the refinement using their index.
set Refinement criteria fields = n, psi

\# Set the maximum and minimum value of the fields where the mesh should be refined
set Refinement window max = 0.99
set Refinement window min = 0.01

where each of the refinement window max/min lists should have a list of values of the same size as the number of refinement criteria fields.

**Comment by landinjm** [comment]
This is no longer how AMR works. Marking as stale.
