### ISSUE TITLE
List of checkpoints is ignored if number of checkpoints of set to zero

### ISSUE THREAD

**Issue by david-montiel-t** [prisms-center/phaseField#123]
In the file parameters.in, when 'Checkpoint condition'  is set to 'LIST', the 'List of time steps to save checkpoints' is ignored if 'Number of checkpoints' is set to zero. 

This should not be that case, since 'Number of checkpoints' should be ignored for the 'LIST' setting.

**Comment by stvdwtt** [comment]
Fixed in v2.1.2
