### ISSUE TITLE
Make sure precipitateEvolution documentation matches the code

### ISSUE THREAD

**Issue by stvdwtt** [prisms-center/phaseField#134]
Currently, the documentation gives the standard 3rd order interpolation function but the code actually uses the standard 5th order interpolation function.

Also, the documentation includes the Landau term even though the code doesn't have it.

The documentation and the code should match. (Note this could have knock-on effects on problem 7 here: https://github.com/prisms-center/PRISMS-PF_Training_Materials/blob/master/PRISMS-PF%20Exercises.pdf)

**Comment by david-montiel-t** [comment]
Documentation has been fixed.
