### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by stvdwtt** [prisms-center/phaseField#148]
The current Docker image is outdated (maybe v2.1), it needs to be updated. We need to have a better way of keeping this up-to-date. At the very least it should be updated with every release.

Also, it is currently associated with my account. That's not ideal. We should have either a PRISMS account or a dedicated PRISMS-PF account.

@david-montiel-t I recommend that you talk to @bpuchala about if there is interest in a PRISMS Docker account.

**Comment by david-montiel-t** [comment]
The Docker image has been updated. Refer to 
https://prisms-center.github.io/phaseField/doxygen_files/install_prismspf.html 
for updated installation instructions.
