### ISSUE TITLE
phaseField v2.1.2 build fails

### ISSUE THREAD

**Issue by ohcfe** [prisms-center/phaseField#153]
I am trying to build PRISMS-PF on my workstation, the build fails [I have pasted the build output here](https://gist.github.com/ohcfe/c4ce0f1a9704999d23caa79fb27c41a8)

my build environment is an up-to-date arch linux workstation, whith the latest version of deal.ii from AUR 9.1.1-2

The most pertinent error from build.log seems to be this:
```bash
/home/mgesing/src/phaseField/src/matrixfree/checkpoint.cc:66:13: error: no matching function for call to ‘dealii::parallel::distributed::Triangulation<2, 2>::save(const char [13])’
   66 |             triangulation.save ("restart.mesh");
      |             ^~~~~~~~~~~~~
In file included from /usr/include/deal.II/fe/mapping.h:26,
                 from /usr/include/deal.II/fe/fe.h:26,
                 from /usr/include/deal.II/fe/fe_system.h:27,
                 from /home/mgesing/src/phaseField/src/matrixfree/../../include/matrixFreePDE.h:15,
                 from /home/mgesing/src/phaseField/src/matrixfree/checkpoint.cc:1:
/usr/include/deal.II/grid/tria.h:3436:3: note: candidate: ‘template<class Archive> void dealii::Triangulation<dim, spacedim>::save(Archive&, unsigned int) const [with Archive = Archive; int dim = 2; int spacedim = 2]’
 3436 |   save(Archive &ar, const unsigned int version) const;
      |   ^~~~
/usr/include/deal.II/grid/tria.h:3436:3: note:   template argument deduction/substitution failed:
/home/mgesing/src/phaseField/src/matrixfree/checkpoint.cc:66:13: note:   candidate expects 2 arguments, 1 provided
   66 |             triangulation.save ("restart.mesh");
      |             ^~~~~~~~~~~~~

```

Has the API for deal.ii changed? Should I be building against a different version of deal.ii?

**Comment by david-montiel-t** [comment]
Hello,

Let me look into this and I will get back to you later.

David

**Comment by david-montiel-t** [comment]
Have you tried building with a previous version of deal.ii?

**Comment by ohcfe** [comment]
> Have you tried building with a previous version of deal.ii? 

I am currently building deal.ii  9.0.0 to try and build against that. . . I'll update this issue when I try building against that.

**Comment by david-montiel-t** [comment]
Thank you!

**Comment by ohcfe** [comment]
I'm having difficulties compiling deal.ii 9.0.0 to run this test, it turns out my version of BOOST is too new and I'm running into [this issue](https://github.com/dealii/dealii/issues/7934). . . I may give it one more try by trying to get an old version of BOOST installed in order to compile the old version of deal.ii in order to compile phaseField. . . Or I may just switch to a machine using a less-frequently-updated linux distro for this work.

**Comment by david-montiel-t** [comment]
Thank you for the update.

I hope either of those options work.

We will look into this.

David

**Comment by ohcfe** [comment]
I managed to build deal.ii 9.0.0 on a system running CentOS 7. I was able to reproduce the same way of phaseField 2.1.2, see the [build log here ](https://gist.github.com/ohcfe/8e37efcb3d9fb15784ea2794ad2e2939)

**Comment by ohcfe** [comment]
Looking at  the [commands used to make the docker image](https://hub.docker.com/layers/stvdwtt/prismspf/prismspf/images/sha256-81af92dd9c8493627067c47fd156c9238aabb8264fb8315f615d189cb3d376f5)
I can see the versions of all the deal.II dependancies that are being used (lines  44-58) and the cmake command used to start the deal.II build (line 62). I think I need to chase down these specific package versions for all the dependencies, build them, and then use that command to build deal.II in the way phaseField expects. It'll take some time, but I'll give it a try.

**Comment by david-montiel-t** [comment]
Thank you for the update.

Let me know if you run into any particular issues I can help with.

Best,

David

**Comment by ohcfe** [comment]
I could use some help navigating which features are required on some of the larger dependancies for deal.ii:
opencascade, hdf5, and trilionos are large packages on their own, which have many configuration options themselves. It would be helpful if you could share which are the important features from these for prisms-phaseField

**Comment by ohcfe** [comment]
Also, it would be useful to know which dependencies in the dependency tree are only required at compile time, and which are shared libraries which need to be accessible to run phaseField

**Comment by david-montiel-t** [comment]
Hello, ohcfe. I will check on that and will get back to you tomorrow.

David

**Comment by stvdwtt** [comment]
I believe the only dependencies are boost, mpi, p4est, and blas. You definitely don’t need to build petsc, slepsc, opencascade, trilinos, or hdf5.

Off the top of my head I can’t remember what you only need at compile time. I think at the very least you need dealii and p4est in your path at run time.

**Comment by ohcfe** [comment]
@stvdwtt I'm getting my information about dependencies from 
the following command:
`docker history stvdwtt/prismspf:prismspf --no-trunc`

```bash
ENV DEAL_II_DIR=/home/dealii/dealii-v9.0.0
ENV SCALAPACK_DIR=/home/dealii/libs/petsc-3.7.6
ENV TRILINOS_DIR=/home/dealii/libs/trilinos-release-12-10-1
ENV SUPERLU_DIR=/home/dealii/libs/superlu_dist_5.1.2
ENV SUNDIALS_DIR=/home/dealii/libs/sundials-3.1.0
ENV SLEPC_DIR=/home/dealii/libs/slepc-3.7.3
ENV PETSC_DIR=/home/dealii/libs/petsc-3.7.6
ENV PARMETIS_DIR=/home/dealii/libs/parmetis-4.0.3
ENV P4EST_DIR=/home/dealii/libs/p4est-2.0
ENV OPENCASCADE_DIR=/home/dealii/libs/oce-OCE-0.18.2
ENV NANOFLANN_DIR=/home/dealii/libs/nanoflann-v1.2.3
ENV METIS_DIR=/home/dealii/libs/parmetis-4.0.3
ENV HDF5_DIR=/home/dealii/libs/hdf5-1.10.1
ENV ASSIMP_DIR=/home/dealii/libs/assimp-3.3.1
ENV ARPACK_DIR=/home/dealii/libs/arpack-ng-3.6.2
ENV ADOLC_DIR=/home/dealii/libs/adolc-2.6.4-rc1
ENV HOME=/home/dealii
ENV FF=mpif77
ENV FC=mpif90
ENV CXX=mpicxx
ENV CC=mpicc
ENV USER=dealii
ENV HOME=/home/dealii
ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LANG=en_US.UTF-8
BUILD_TYPE=DebugRelease VER=v9.0.0 /bin/sh -c git clone \
    https://github.com/dealii/dealii.git dealii-$VER-src && \
    cd dealii-$VER-src &&  \
    git checkout $VER &&  \
    mkdir build && cd build &&  \
    cmake -DDEAL_II_WITH_MPI=ON \
	-DDEAL_II_COMPONENT_EXAMPLES=OFF \
        -DCMAKE_INSTALL_PREFIX=~/dealii-$VER \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE  \
        -GNinja   \
        ../ &&  \
    ninja install &&  \
    ninja test &&  \
    cp summary.log ~/dealii-$VER/summary.log && \
    cd .. && rm -rf build .git
```

you say:
> I believe the only dependencies are boost, mpi, p4est, and blas.
> You definitely don’t need to build petsc, slepsc, opencascade, trilinos, or hdf5.

If the others are not necessary, why are they included with the docker image?

**Comment by stvdwtt** [comment]
@ohcfe The docker image builds off of the standard deal.ii docker image. They add pretty much every possible package that deal.ii interfaces with so that the image is useful to the broadest audience. We only use a small subset of the libraries that deal.ii can interface with so you don't have to install all of them.

**Comment by stvdwtt** [comment]
@ohcfe Also, I checked the deal.ii API and it doesn't seem to have changed for the save method of parallel::distributed::triangulation. I'm really unclear on why you'd get this error.

Your error log shows that save is being called for the non-distributed triangulation (with one argument instead of two). I'm not clear why that is being called at all. The triangulation is distributed, which has its own save method.

**Comment by ohcfe** [comment]
> @ohcfe Also, I checked the deal.ii API and it doesn't seem to have changed for the save method of parallel::distributed::triangulation. I'm really unclear on why you'd get this error.
> 
> Your error log shows that save is being called for the non-distributed triangulation (with one argument instead of two). I'm not clear why that is being called at all. The triangulation is distributed, which has its own save method.

Steps to reproduce my error, in case you want  to debug the mysterious calls to non-distributed triangulation:
```bash
cd ~/src
git clone https://github.com/dealii/dealii.git
cd dealii
git checkout v9.0.0
mkdir build
cd build
sudo mkdir /opt/dealii
sudo chown myUser:myUser /opt/dealii
cmake -DCMAKE_INSTALL_PREFIX=/opt/dealii/9.0.0
make -j18 install
cd ~/src
git clone https://github.com/prisms-center/phaseField.git
cd phaseField
git checkout v2.1.2
mkdir build
cd build
cmake3 -Ddeal.II_DIR=/opt/dealii/9.0.0/lib/cmake/deal.II ../
make -j18
```

**Comment by wangtianle576** [comment]
I have the same problem as you. Could you tell me how to solve this problem about PRISMS-PF installing, thank you.

**Comment by david-montiel-t** [comment]
Hello wangtianle576,

Can you please provide the following information:

1) What is the platform and operating system (including version) you are
using?

2) What the deal.II installation you are using, and how did you install it?

3) What PRISMS-PF installation are you using (traditional or Docker-based)?

4) What error message are you getting and in what step of the compilation?

Thank you,

David
