### ISSUE TITLE
Fail to run example 

### ISSUE THREAD

**Issue by qingyang0315** [prisms-center/phaseField#169]
When I try to run the example of "allenCahn" in the folder "/phaseField/applications/allenCahn", it shows that "An error occurred in line <551> of file </home/yq/deal.ii-candi/tmp/unpack/deal.II-v9.2.0/source/base/parameter_handler.cc> in function
    virtual void dealii::ParameterHandler::parse_input(const string&, const string&, bool, bool)
The violated condition was:  
    false
Additional information: 
    Unknown input file name extension. Supported types are .prm, .xml, and .json." But the input file is "parameters.in". I wonder why. Thanks.

**Comment by david-montiel-t** [comment]
Hello qingyang0315

I am working on resolving this issue.

In the meantime can you try the following steps to run your code?

1) rename the file parameters.in as parameters.prm

2) Run the code using parameters.prm that as your non-standard input file
(e.g. "$ ./main -i parameters.prm").

Sorry for the late reply.,

I hope this helps,

David

**Comment by qingyang0315** [comment]
Thanks for your help. In the recent  release version, New Alloy Solidification application is released. However, i cannot understand the "grad_phi and grad_U dot product term" and required equations of "U", especially the gradient of anti-trapping term Jat.
