### ISSUE TITLE
Description of the scripts and mathematical representation

### ISSUE THREAD

**Issue by Shahid718** [prisms-center/phaseField#172]
Under the description of the following scripts, there is some confusion

**phase_fraction.py**

- (volume fraction for 2D, area fraction for 3D)

Is it volume fraction for 3D and area fraction of 2D?

- $\phi=\frac{1}{V}\int_V n,d^3r $

This mathematical format for the formula is hard to understand. Is there any way to have a symbolic mathematical representation of the expressions?

**domain_count.py**

- Each interconnected region for which n<-0.5 is counted as a separate domain.

Is that an arrow sign with 0.5 or less than negative 0.5?

**Comment by david-montiel-t** [comment]
Thank you for pointing this out, Shahid. The LaTeX equations were not rendered properly. It has now been fixed.
