### ISSUE TITLE
No matching function for call to " weightedDistanceFromNucleusCenter"

### ISSUE THREAD

**Issue by qingyang0315** [prisms-center/phaseField#176]
When I run the example "/_nucleating_precipitates_MgRE" it shows the mistake of 
error: no matching function for call to ‘customPDE<2, 1>::weightedDistanceFromNucleusCenter(const dealii::Point<2, double>&, std::vector<double, std::allocator<double> >, dealii::Tensor<2, 2, double>, const dealii::Point<2, dealii::VectorizedArray<double, 2> >&, const unsigned int&) const’  dealii::VectorizedArray<double> 
weighted_dist = this->weightedDistanceFromNucleusCenter(thisNucleus->center,“
But other examples can be run successfully.
I reallly need your help 
Thanks.

**Comment by david-montiel-t** [comment]
Hello, qingyang0315

Thank you for reporting this.

I will look into it and get back to you soon.

Best,

David

**Comment by david-montiel-t** [comment]
I just realized that *_nucleating_precipitates_MgRE* is an application
under development and is not fully compatible with the latest version of
PRISMS-PF

Is there a particular feature of this application that you want to use in
your simulation?

Best,

David
