### ISSUE TITLE
Problem in Loading Initial Conditions from File for AllenCahn Example application

### ISSUE THREAD

**Issue by ksnvikrant** [prisms-center/phaseField#181]
The example AllenCahn with loading initial conditions is not working. It initiated the .vtk file but not proceeding after 'Applying PField initial condition...'

The output is as follows:

Using the input parameter file: parameters_pfield.prm
Number of constants: 2
Number of post-processing variables: 2
creating problem mesh...
periodic facepairs: 0
problem dimensions: 100x100
number of elements: 65536

initializing matrix free object
initializing finite element space P^1 for EXPLICIT_TIME_DEPENDENT:SCALAR field 'n'
field ' n' DOF : 66049 (Constraint DOF : 0)
total DOF : 66049
Begin reading vtk file
Begin reading vtk file
Begin reading vtk file
initializing parallel::distributed residual and solution vectors
computed mass matrix (using FE space for field: 0)
Begin reading vtk file
Read POINTS: 32768
  reserve OK
  done
Determine Body size
  Min Coordinate: 0 0 
  Max Coordinate: 100 50 
  done
Initialize Bin
  done
Read CELLS: 8192
  done
Bin interpolating functions
  done  max_bin_size: 16
begin reading data
  done
Construct PField 'n'
  done
Applying PField initial condition...

**Comment by david-montiel-t** [comment]
Ah, yes. I remember encountering that.

Thank you, Steve.

I will make a note on the parameters_pfield.prm file.

David
