### ISSUE TITLE
Issue at corner node when a variable of TIME_INDEPENDENT equation type and some boundary conditions

### ISSUE THREAD

**Issue by david-montiel-t** [prisms-center/phaseField#182]
Whenever NATURAL or PERIODIC boundary conditions are used for a variable of TIME_INDEPENDENT equation type, the (0,0) corner node is "pinned" to zero if mesh adaptivity is enabled.

**Comment by david-montiel-t** [comment]
The pinning at the corner has been disabled for variables associated with TIME_INDEPENDENT equation types. This means that the code may not be able to find a unique solution for TIME_INDEPENDENT equations that include only spatial derivatives of the variable if no DIRICHLET boundary conditions are present. A functionality to handle this particular case should be implemented.

**Comment by landinjm** [comment]
I think we should let the user specify which fields and where the solution is constrained. 

It should be obvious when the solution is unconstrained and needs to be, so automatically assigning this based on the user specified dependencies is not worth the trouble.

That said, changing this will make the current unit test obsolete.
