### ISSUE TITLE
Mismatch between alloySolidification documentation and implementation

### ISSUE THREAD

**Issue by stvdwtt** [prisms-center/phaseField#188]
See: https://groups.google.com/g/prisms-pf-users/c/38ZUeIT3wNs

(Text copied from Google Groups)
The Echebarria et al. paper (10.1103/PhysRevE.70.061604) that is referenced gives two ways to calculate the relaxation time, tau0. One in Eq 121 and one in Eq 123. The governing equations they give in Eqs 132-133 use the Eq 121 expression (for reasons that I don't believe are clearly stated). These are the equations in the alloySolidification documentation. However, the actual code seems to use the Eq 123 expression. That expression was used in the 2008 Farzadi et al. paper (doi:10.1088/0965-0393/16/6/065005, also for reasons that I don't believe are clearly stated). The documentation and the code need to match. I'd also be interested to know what motivated the use of the Eq 123 expression.

Second, the code has a parameter U_off that shifts the interface temperature. This variable shows up in the code but is not in the governing equations.

Third, the code has a parameter y0 that controls the radius of the initial seed. The documentation seems to imply that y0 controls the location of a planar interface.

**Comment by david-montiel-t** [comment]
Fixed all three of these issues. Might need a better justification for choosing Eq 121 from Echebarria et al.
