### ISSUE TITLE
 input parameter inconsistency  for weightedDistanceFromNucleusCenter function 

### ISSUE THREAD

**Issue by zzzmx-josh** [prisms-center/phaseField#200]
In the `seedNucleus` function located in `applications/_nucleating_precipitates_MgRE/equations.h`, there seems to be a discrepancy related to the usage of the `weightedDistanceFromNucleusCenter` method. The function requires the `nucleus_rot_matrix`, calculated by `get_nucleus_rotation_matrix`, as a parameter. However, the original `weightedDistanceFromNucleusCenter` method does not require this rotation matrix as a parameter. Instead, the rotation matrix is directly used in the method through `shortest_edist_tensor = userInputs.get_nucleus_rotation_matrix(var_index) * shortest_edist_tensor`.

As a result, compiling this app as it stands might result in an error due to this inconsistency. Should I consider removing the `nucleus_rot_matrix` input parameter from the `seedNucleus` function to align it with the `weightedDistanceFromNucleusCenter` method's logic ？

**Comment by david-montiel-t** [comment]
Thank you for reporting this issue, Josh. I will have a look.

**Comment by landinjm** [comment]
I don't believe an overload for this function ever existed with a rotation matrix input. Given that `_nucleating_precipitates_MgRE` was a work in progress application (that has now been deprecated), I am marking this as won't fix.

**Comment by landinjm** [comment]
Marking as wontfix
