### ISSUE TITLE
Github Actions CI

### ISSUE THREAD

**Issue by landinjm** [prisms-center/phaseField#227]
Implement a basic CI with GitHub Actions so we don't run into issues like #224, or at least find them sooner.

**Comment by stvdwtt** [comment]
Did the CI through Travis CI break?

If so, I'd recommend removing the `.travis.yml` file and edit/remove the Travis CI badge in the README.

**Comment by landinjm** [comment]
I think it did.

I can edit the README to replace the Travis CI with GitHub Actions icons.

**Comment by landinjm** [comment]
Should be working (minus issues with unit tests `OrderParameterRemapper` & `FloodFiller`
