### ISSUE TITLE
Issue compiling cahn example

### ISSUE THREAD

**Issue by aeleuterio** [prisms-center/phaseField#37]
Hi folks,
I'm trying to compile the cahnHilliard example. I have deal II installed and after successfully running cmake, I get the following error with make:
```
/home/workgroups/reit/packages/phase-field/phaseField-1.0/applications/cahnHilliard/../../src/models/coupled/generalized_model_functions.h:1026:60: error: 'MPI_Send' was not declared in this scope
       MPI_Send(&numNuclei, 1, MPI_INT, 0, 0, MPI_COMM_WORLD);
```

I get similar errors for MPI_Barrier, MPI_Recv. MPI_DOUBLE, MPI_INT and more.
I have the MPI environment set up right; I have tested it with different combinations of intel and openmpi and no luck.
Any pointers?
Thank you

**Comment by stvdwtt** [comment]
Hi Andre,
I'm sorry to hear that you're running into an issue. I'll do my best to help you get up and running as soon as possible.

On Friday, someone else sent me a similar issue. I haven't tracked down what the issue is.

A couple questions to see how similar your situation is to that one:
1) What is your operating system?
2) Did you have MPI installed on your machine before downloading deal.II?
3) What compiler are you using? (From your comment, I'm guessing the Intel compiler? Have you tried any others?)

**Comment by aeleuterio** [comment]
Hi @stvdwtt, thank you for the prompt reply.

1) I'm on a cluster running RHEL 7.
2) Yes, both intel's MPI and OpenMPI
3) I used GNU and Intel to the same results

Let me know any other info I could provide

**Comment by stvdwtt** [comment]
Could you try running the deal.ii step 48 tutorial on multiple cores to make sure that the connection between deal.II and MPI works as expected? You can find the step 48 tutorial in the Resources/examples/ directory where you installed deal.II.

**Comment by aeleuterio** [comment]
I was able to successfully run step-48. It's a very large output with several files - if you want I can share via email or something

**Comment by aeleuterio** [comment]
Looking more closely to the error output of making the cahnHiliard application, I saw this error:

```
error: no matching function for call to 'dealii::parallel::distributed::Triangulation<2, 2>::Triangulation(MPI_Comm)'
  computing_timer (pcout, TimerOutput::summary, TimerOutput::wall_times)
```
Looks like a deal II error; although I ran tests on deall II and passed

**Comment by stvdwtt** [comment]
The other person saw a similar error. When you installed deal.II, did you link it to your cluster's MPI library or did you use the MPI library that comes with deal.II?

Also, what compiler did you use to compile deal.II?

**Comment by aeleuterio** [comment]
I linked it to my cluster's MPI.
I compiled deal.II with OpenMPI's mpicc/mpic++

**Comment by stvdwtt** [comment]
Hi Andre,
Could you check the "summary.log" file in the deal.II build directory? The log file should have a list of which features/libraries deal.II was configured with.

Does it say:
DEAL_II_WITH_P4EST = OFF
or
DEAL_II_WITH_P4EST set up with external dependencies

If DEAL_II_WITH_P4EST is set to OFF, you need to install p4est and then reinstall deal.II. You can find directions on how to do that here:
https://www.dealii.org/developer/external-libs/p4est.html

Sorry, this is something that we need to add to the User Guide.

Let me know if this works.

**Comment by aeleuterio** [comment]
Indeed I have `DEAL_II_WITH_P4EST = OFF`
I'll recompile and get back to you asap

**Comment by aeleuterio** [comment]
Ok now I have
`DEAL_II_WITH_P4EST set up with external dependencies`
but when building the cahn application with the new deal II build (I checked and it's pointing to the new build), I'm getting errors such as:
`/dealii/8.4.1-withp4/include/deal.II/base/vectorization.h(1559): error: no operator "+=" matches these operands`

I get similar error for operands such as -=, *=, /= etc

**Comment by stvdwtt** [comment]
Could you give me the whole error? I want to see where the += operator is being used.

**Comment by aeleuterio** [comment]
@stvdwtt it worked!
I reinstalled p4est and deal II with gcc 4.8.5 and OpenMPI 2.01.
For p4est I set the compilers and then:
```
./configure --prefix=/path/to/p4/ --enable-mpi
make
make install
```

For deal II I ran:
```
cmake -DCMAKE_INSTALL_PREFIX=/path/to/dealII -DP4EST_DIR=/path/to/p4/ -DDEAL_II_WITH_P4EST=ON -DDEAL_II_WITH_MPI=ON /path/to/dealIIsources/
make
make install
```

If there's any more info I can provide let me know; thank you very much!

**Comment by stvdwtt** [comment]
Great, I'm glad you were able to get it to work!
