### ISSUE TITLE
Issue with Voigt Notation in elasticity tensor (/src/models/mechanics/anisotropy.h)

### ISSUE THREAD

**Issue by agkrish** [prisms-center/phaseField#38]
Hi,
I feel there is a slight issue with Voigt notation for 2D model as described in the comments in anisotropy.h file.

![voigt_notation](https://cloud.githubusercontent.com/assets/22416968/20357555/6f6b0cde-abf6-11e6-9954-cd3f9160e01b.png)

In the 2D model anisotropy (6 constants), instead of [C11 C22 C33 C12 C13 C23] it should be [C11 C22 C66 C12 C16 C26]

~ Geetha Krishna

**Comment by stvdwtt** [comment]
Hi Geetha,
If you have a chance, feel free to make that fix and submit a pull request to the "next" branch. If you need help doing that, let me know.

-Steve

**Comment by agkrish** [comment]
Hi,

I will try doing that and I will update you in that regard

Regards
Geetha Krishna A

**Comment by stvdwtt** [comment]
Fixed in v1.1.1
