### ISSUE TITLE
Four extra lines must be deleted for CHAC_anisotropy application?

### ISSUE THREAD

**Issue by qixinbo** [prisms-center/phaseField#40]
Dear developers:
I have found that there are four extra lines in CHAC_anisotropy and CHAC_anisotropyRegularized. 
They are Lines 38-41 at the ICs_and_BCs.h:
`		  r=p.distance(Point<dim>(spanX/3.0,spanY/3.0));
		  scalar_IC = 0.5*(1.0-std::tanh((r-spanX/5.0)/(3*dx)));
		  r=p.distance(Point<dim>(3.0*spanX/4.0,3.0*spanY/4.0));
		  scalar_IC += 0.5*(1.0-std::tanh((r-spanX/12.0)/(3*dx)));`
When the dimension of the problem is set to be 3, then they will cause an error, since the dim in above code is refined to be 2.

**Comment by stvdwtt** [comment]
Nice catch, thank you. I'll fix that in the next update. Or, if you'd like, you can make the change and submit a push request to the "next" branch, and I'll merge it in.

**Comment by qixinbo** [comment]
I have made a push request regarding this issue, please check it.
Thank you very much!

**Comment by stvdwtt** [comment]
Fix merged in.
