### ISSUE TITLE
dendritic-growth simulation has succeed using prisms-pf

### ISSUE THREAD

**Issue by qixinbo** [prisms-center/phaseField#43]
Dear Steve:
A new example of using prisms-pf to simulate dendritic-growth has been conducted. The results are as follows:
[2D](http://7xrm8i.com1.z0.glb.clouddn.com/2D.gif)
[3D](http://7xrm8i.com1.z0.glb.clouddn.com/3D.gif)

Thank you so much!

My code is here:
[code](https://github.com/qixinbo/phaseField/tree/next/applications/dendriticGrowth)

However, currently, I cannot make a pull request, since I made some changes in the basic framework of prisms-pf. 
For example, the governing equations of dendritic growth need two sets of SolutionSet: the current one solutionSet and the last one oldSolutionSet. So I change the solutionSet in the functions of computeRHS, getRHS and residualRHS to a vector containing solutionSet and oldSolutionSet. 

I hope the main framework of prisms-pf can add a feature of receiving several sets of solutions in the RHS construction (or it has already such a feature?), so I can change my code and make a pull request to the main branch. 

Xin-Bo Qi

**Comment by stvdwtt** [comment]
Hi Xin-Bo,
Great! I'll start looking through your changes to figure out how to generalize the existing framework to include this functionality.

Is there a particular paper you got your solidification model from? Having a little more familiarity with the model will help me parse the code. Thanks!

**Comment by qixinbo** [comment]
Hi Steve,
The code is based on the model by Wheeler et al.
See: [here](http://www.sciencedirect.com/science/article/pii/016727899390242S)
The anisotropy part refers to Karma's [model](http://www.sciencedirect.com/science/article/pii/016727899390242S), in order to handle the 3D case. And it can be deduced to the style in Wheeler's model in 2D case.

Xin-Bo

**Comment by stvdwtt** [comment]
Hi Xin-Bo,
After some thought, I think there are two ways to access the time derivative without a major change to the framework.

First of all, just to make sure that I'm clear on the issue, you need the old solution to calculate the time derivative of the order parameter for the heat equation, right? You should be able to calculate that from your residual for the order parameter -- to update the order parameter you use it's time derivative.

![image](https://cloud.githubusercontent.com/assets/10517751/21744898/1ce80ee2-d4ed-11e6-95b5-3440ebe3bfec.png)

If you do absolutely need access to the old value of the order parameter, you could create it as a third variable (so you'd have temp, eta, and eta_old as variables). Then you just set eta_old = eta in residualsRHS and it'll have the value of eta from the previous time step.

Let me know if this makes sense and you think either way will work.

Best,
Steve

**Comment by qixinbo** [comment]
Thanks, Steve, I think both ways are feasible. 
In my pinion, the first way is not quite elegant, so I prefer the second one. 
However, I don't know how to pass eta_old into residualRHS without modifying the framework. Just as the way in my code, I changed the parameter "std::vector<modelVariable<dim>>" to a Vector style "std::vector<std::vector<modelVariable<dim>>>" in order to accept eta and eta_old.

**Comment by stvdwtt** [comment]
In v2.0 a dendritic solidification app was added, very similar to the one here.
