### ISSUE TITLE
1D calculations are not supported

### ISSUE THREAD

**Issue by stvdwtt** [prisms-center/phaseField#66]
deal.II doesn't support distributed 1D triangulations. If we want to support true 1D calculations we would need to add support for a non-distributed triangulation. Currently, 1D simulations should be implemented as degenerate 2D simulations. The PRISMS-PF documentation should be updated to reflect this.

**Comment by landinjm** [comment]
As mentioned in #294, we can simply do something like this
```
  using Triangulation =
    std::conditional_t<dim == 1,
                       dealii::Triangulation<dim>,
                       dealii::parallel::distributed::Triangulation<dim>>;
```
to run in 1D. For the sake of debugging code, we can get over the fact that triangulation might be stored on every processor.
