### ISSUE TITLE
stress visualization for PF

### ISSUE THREAD

**Issue by rudraa** [prisms-center/phaseField#7]
stress visualization for PF

**Comment by stvdwtt** [comment]
Implementation of a post-processing suite is planned. Right now the best way is to add another variable with a residual corresponding to the desired output (e.g. stress, strain, elastic energy density). This slows down the calculation and is obviously suboptimal.

**Comment by stvdwtt** [comment]
The postprocessing suite will be included in the release of v1.2, planned for May 2017. I'm finishing up some testing and should be pushing to "reorganized_library" in the near future.

**Comment by stvdwtt** [comment]
Available on the "master" branch now
