### ISSUE TITLE
Duplicate documentation in precipitateEvolution folder

### ISSUE THREAD

**Issue by jpluce** [prisms-center/phaseField#83]
There are two pdfs files in the precipitateEvolution applications folder, formulation_precipitateEvolution.pdf and precipitateEvolution.pdf. They both appear to have the same roughly the same content, although the commit comments suggest precipitateEvolutioin.pdf is an update to formulation_precipitateEvolution.pdf. To avoid confusion, I would suggest removing one of the pdf files.

**Comment by stvdwtt** [comment]
Fixed in v2.0.1(pre)
